"""
Interactive Mojito L1 data processing.

Load and combine Mojito L1 packages, run ``MojitoProcessor.process_pipeline``,
plot results, and save Mojito L1–compatible HDF5 output.
"""

from mojito_barkeeper.defaults import mojito_preprocessing_pipeline_kwargs
from mojito_barkeeper.lab import (
    AET_CHANNELS,
    CADENCE_CHOICES,
    L1_TDI_DATASETS,
    MAX_UI_SCALE,
    MIN_UI_SCALE,
    PACKAGE_FAMILIES,
    SECONDS_PER_DAY,
    SECONDS_PER_HOUR,
    STATE_PATH,
    TDI_ATTRIBUTES,
    TIME_UNITS,
    UI_SCALE_CHOICES,
    XYZ_CHANNELS,
    Contribution,
    DataPackage,
    GuiState,
    PipelineError,
    PipelineSettings,
    ProcessedResult,
    SaveOptions,
    TimeWindow,
    amplitude_spectral_density,
    clamp_ui_scale,
    combine_packages,
    default_package_label,
    discover_packages,
    is_saved_pipeline_output,
    load_gui_state,
    load_package_tdi,
    package_family,
    process,
    run_pipeline,
    save_gui_state,
    save_result,
    segment_to_result,
    suggest_ui_scale,
)

__all__ = [
    "AET_CHANNELS",
    "CADENCE_CHOICES",
    "Contribution",
    "DataPackage",
    "GuiState",
    "L1_TDI_DATASETS",
    "MAX_UI_SCALE",
    "MIN_UI_SCALE",
    "PACKAGE_FAMILIES",
    "PipelineError",
    "PipelineSettings",
    "ProcessedResult",
    "SaveOptions",
    "SECONDS_PER_DAY",
    "SECONDS_PER_HOUR",
    "STATE_PATH",
    "TDI_ATTRIBUTES",
    "TIME_UNITS",
    "TimeWindow",
    "UI_SCALE_CHOICES",
    "XYZ_CHANNELS",
    "amplitude_spectral_density",
    "clamp_ui_scale",
    "combine_packages",
    "default_package_label",
    "discover_packages",
    "is_saved_pipeline_output",
    "load_gui_state",
    "load_package_tdi",
    "mojito_preprocessing_pipeline_kwargs",
    "package_family",
    "process",
    "run_pipeline",
    "save_gui_state",
    "save_result",
    "segment_to_result",
    "suggest_ui_scale",
]

__version__ = "0.1.0"
